Revert "sm8250-common: Compile the kernel without GCC"
n0 based kernels still need it.
fixes

/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/atomic_lse.h:45:1: error: unknown register name 'w0' in asm
   45 | ATOMIC_OP(or, stset)
      | ^
/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/atomic_lse.h:32:23: note: expanded from macro 'ATOMIC_OP'
   32 |         register int w0 asm ("w0") = i;                                 \
      |                              ^
/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/atomic_lse.h:45:1: error: unknown register name 'x1' in asm
/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/atomic_lse.h:33:29: note: expanded from macro 'ATOMIC_OP'
   33 |         register atomic_t *x1 asm ("x1") = v;                           \
      |                                    ^
/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/atomic_lse.h:45:1: error: unknown register name 'x16' in asm
/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/atomic_lse.h:41:4: note: expanded from macro 'ATOMIC_OP'
   41 |         : __LL_SC_CLOBBERS);                                            \
      |           ^
/mnt/aosp/luna/kernel/xiaomi/sm8250/arch/arm64/include/asm/lse.h:32:26: note: expanded from macro '__LL_SC_CLOBBERS'
   32 | #define __LL_SC_CLOBBERS        "x16", "x17", "x30"

This reverts commit 5a8a0b4b76e07598a6095babc570de112ef12cc8.